/* --- БАЗА ДАННЫХ СЛОВ (Oxford 5000 - Часть 1) --- */
const rawWords = [
  {
    word: 'a, an',
    type: 'indefinite article',
    level: 'A1',
    translation: 'неопределенный артикль',
    phonetic: '[ə, æn]',
  },
  {
    word: 'abandon',
    type: 'v.',
    level: 'B2',
    translation: 'покидать, оставлять',
    phonetic: '[əˈbændən]',
  },
  {
    word: 'ability',
    type: 'n.',
    level: 'A2',
    translation: 'способность, умение',
    phonetic: '[əˈbɪləti]',
  },
  { word: 'able', type: 'adj.', level: 'A2', translation: 'способный', phonetic: '[ˈeɪbl]' },
  {
    word: 'about',
    type: 'prep., adv.',
    level: 'A1',
    translation: 'о, около, приблизительно',
    phonetic: '[əˈbaʊt]',
  },
  {
    word: 'above',
    type: 'prep., adv.',
    level: 'A1',
    translation: 'над, выше',
    phonetic: '[əˈbʌv]',
  },
  { word: 'abroad', type: 'adv.', level: 'B2', translation: 'за границей', phonetic: '[əˈbrɔːd]' },
  {
    word: 'absolute',
    type: 'adj.',
    level: 'B2',
    translation: 'абсолютный, полный',
    phonetic: '[ˈæbsəluːt]',
  },
  {
    word: 'absolutely',
    type: 'adv.',
    level: 'B1',
    translation: 'совершенно, безусловно',
    phonetic: '[ˌæbsəˈluːtli]',
  },
  {
    word: 'academic',
    type: 'adj.',
    level: 'B1',
    translation: 'академический, учебный',
    phonetic: '[ˌækəˈdemɪk]',
  },
  {
    word: 'accept',
    type: 'v.',
    level: 'A2',
    translation: 'принимать, соглашаться',
    phonetic: '[əkˈsept]',
  },
  {
    word: 'acceptable',
    type: 'adj.',
    level: 'B2',
    translation: 'приемлемый',
    phonetic: '[əkˈseptəbl]',
  },
  {
    word: 'access',
    type: 'n., v.',
    level: 'B1',
    translation: 'доступ, иметь доступ',
    phonetic: '[ˈækses]',
  },
  {
    word: 'accident',
    type: 'n.',
    level: 'A2',
    translation: 'несчастный случай, авария',
    phonetic: '[ˈæksɪdənt]',
  },
  {
    word: 'accompany',
    type: 'v.',
    level: 'B2',
    translation: 'сопровождать',
    phonetic: '[əˈkʌmpəni]',
  },
  {
    word: 'according to',
    type: 'prep.',
    level: 'A2',
    translation: 'в соответствии с, согласно',
    phonetic: '[əˈkɔːrdɪŋ tu]',
  },
  {
    word: 'account',
    type: 'n. (B1), v. (B2)',
    level: 'B1/B2',
    translation: 'счет, отчет; считать за',
    phonetic: '[əˈkaʊnt]',
  },
  {
    word: 'accurate',
    type: 'adj.',
    level: 'B2',
    translation: 'точный, правильный',
    phonetic: '[ˈækjərət]',
  },
  { word: 'accuse', type: 'v.', level: 'B2', translation: 'обвинять', phonetic: '[əˈkjuːz]' },
  { word: 'achieve', type: 'v.', level: 'A2', translation: 'достигать', phonetic: '[əˈtʃiːv]' },
  {
    word: 'achievement',
    type: 'n.',
    level: 'B1',
    translation: 'достижение',
    phonetic: '[əˈtʃiːvmənt]',
  },
  {
    word: 'acknowledge',
    type: 'v.',
    level: 'B2',
    translation: 'признавать, подтверждать',
    phonetic: '[əkˈnɒlɪdʒ]',
  },
  {
    word: 'acquire',
    type: 'v.',
    level: 'B2',
    translation: 'приобретать, овладевать',
    phonetic: '[əˈkwaɪər]',
  },
  {
    word: 'across',
    type: 'prep., adv.',
    level: 'A1',
    translation: 'через, сквозь',
    phonetic: '[əˈkrɒs]',
  },
  {
    word: 'act',
    type: 'v. (A2), n. (B1)',
    level: 'A2/B1',
    translation: 'действовать, акт',
    phonetic: '[ækt]',
  },
  { word: 'action', type: 'n.', level: 'A1', translation: 'действие', phonetic: '[ˈækʃn]' },
  { word: 'active', type: 'adj.', level: 'A2', translation: 'активный', phonetic: '[ˈæktɪv]' },
  {
    word: 'activity',
    type: 'n.',
    level: 'A1',
    translation: 'деятельность, активность',
    phonetic: '[ækˈtɪvəti]',
  },
  { word: 'actor', type: 'n.', level: 'A1', translation: 'актер', phonetic: '[ˈæktər]' },
  { word: 'actress', type: 'n.', level: 'A1', translation: 'актриса', phonetic: '[ˈæktrəs]' },
  {
    word: 'actual',
    type: 'adj.',
    level: 'B2',
    translation: 'фактический, реальный',
    phonetic: '[ˈæktʃuəl]',
  },
  {
    word: 'actually',
    type: 'adv.',
    level: 'A2',
    translation: 'на самом деле, фактически',
    phonetic: '[ˈæktʃuəli]',
  },
  { word: 'ad', type: 'n.', level: 'B1', translation: 'объявление, реклама', phonetic: '[æd]' },
  {
    word: 'adapt',
    type: 'v.',
    level: 'B2',
    translation: 'адаптировать, приспосабливаться',
    phonetic: '[əˈdæpt]',
  },
  { word: 'add', type: 'v.', level: 'A1', translation: 'добавлять', phonetic: '[æd]' },
  { word: 'addition', type: 'n.', level: 'B1', translation: 'дополнение', phonetic: '[əˈdɪʃn]' },
  {
    word: 'additional',
    type: 'adj.',
    level: 'B2',
    translation: 'дополнительный',
    phonetic: '[əˈdɪʃənl]',
  },
  {
    word: 'address',
    type: 'n. (A1), v. (B2)',
    level: 'A1/B2',
    translation: 'адрес; обращаться к',
    phonetic: '[əˈdres]',
  },
  {
    word: 'administration',
    type: 'n.',
    level: 'B1',
    translation: 'администрация, управление',
    phonetic: '[ədˌmɪnɪˈstreɪʃn]',
  },
  { word: 'admire', type: 'v.', level: 'B1', translation: 'восхищаться', phonetic: '[ədˈmaɪər]' },
  {
    word: 'admit',
    type: 'v.',
    level: 'B1',
    translation: 'признавать, допускать',
    phonetic: '[ədˈmɪt]',
  },
  {
    word: 'adopt',
    type: 'v.',
    level: 'B2',
    translation: 'принимать, усыновлять',
    phonetic: '[əˈdɒpt]',
  },
  {
    word: 'adult',
    type: 'n. (A1), adj. (A2)',
    level: 'A1/A2',
    translation: 'взрослый',
    phonetic: '[ˈædʌlt]',
  },
  {
    word: 'advance',
    type: 'n., v., adj.',
    level: 'B2',
    translation: 'продвижение, продвигаться',
    phonetic: '[ədˈvɑːns]',
  },
  {
    word: 'advanced',
    type: 'adj.',
    level: 'B1',
    translation: 'продвинутый, передовой',
    phonetic: '[ədˈvɑːnst]',
  },
  {
    word: 'advantage',
    type: 'n.',
    level: 'A2',
    translation: 'преимущество',
    phonetic: '[ədˈvɑːntɪdʒ]',
  },
  {
    word: 'adventure',
    type: 'n.',
    level: 'A2',
    translation: 'приключение',
    phonetic: '[ədˈventʃər]',
  },
  {
    word: 'advertise',
    type: 'v.',
    level: 'A2',
    translation: 'рекламировать',
    phonetic: '[ˈædvərtaɪz]',
  },
  {
    word: 'advertisement',
    type: 'n.',
    level: 'A2',
    translation: 'рекламное объявление',
    phonetic: '[ədˈvɜːrtɪsmənt]',
  },
  {
    word: 'advertising',
    type: 'n.',
    level: 'A2',
    translation: 'рекламная деятельность',
    phonetic: '[ˈædvərtaɪzɪŋ]',
  },
  { word: 'advice', type: 'n.', level: 'A1', translation: 'совет', phonetic: '[ədˈvaɪs]' },
  { word: 'advise', type: 'v.', level: 'B1', translation: 'советовать', phonetic: '[ədˈvaɪz]' },
  { word: 'affair', type: 'n.', level: 'B2', translation: 'дело, событие', phonetic: '[əˈfeər]' },
  {
    word: 'affect',
    type: 'v.',
    level: 'A2',
    translation: 'влиять, воздействовать',
    phonetic: '[əˈfekt]',
  },
  {
    word: 'afford',
    type: 'v.',
    level: 'B1',
    translation: 'позволить себе (финансово)',
    phonetic: '[əˈfɔːrd]',
  },
  { word: 'afraid', type: 'adj.', level: 'A1', translation: 'испуганный', phonetic: '[əˈfreɪd]' },
  {
    word: 'after',
    type: 'prep. (A1), conj., adv. (A2)',
    level: 'A1/A2',
    translation: 'после',
    phonetic: '[ˈɑːftər]',
  },
  {
    word: 'afternoon',
    type: 'n.',
    level: 'A1',
    translation: 'день (время после полудня)',
    phonetic: '[ˌɑːftəˈnuːn]',
  },
  {
    word: 'afterward',
    type: 'adv.',
    level: 'B2',
    translation: 'впоследствии, потом',
    phonetic: '[ˈɑːftəwəd]',
  },
  { word: 'again', type: 'adv.', level: 'A1', translation: 'снова, опять', phonetic: '[əˈɡen]' },
  { word: 'against', type: 'prep.', level: 'A2', translation: 'против', phonetic: '[əˈɡenst]' },
  {
    word: 'age',
    type: 'n. (A1), v. (B1)',
    level: 'A1/B1',
    translation: 'возраст; стареть',
    phonetic: '[eɪdʒ]',
  },
  { word: 'agency', type: 'n.', level: 'B2', translation: 'агентство', phonetic: '[ˈeɪdʒənsi]' },
  { word: 'agenda', type: 'n.', level: 'B2', translation: 'повестка дня', phonetic: '[əˈdʒendə]' },
  { word: 'agent', type: 'n.', level: 'B1', translation: 'агент', phonetic: '[ˈeɪdʒənt]' },
  {
    word: 'aggressive',
    type: 'adj.',
    level: 'B2',
    translation: 'агрессивный',
    phonetic: '[əˈɡresɪv]',
  },
  { word: 'ago', type: 'adv.', level: 'A1', translation: 'тому назад', phonetic: '[əˈɡəʊ]' },
  { word: 'agree', type: 'v.', level: 'A1', translation: 'соглашаться', phonetic: '[əˈɡriː]' },
  {
    word: 'agreement',
    type: 'n.',
    level: 'B1',
    translation: 'соглашение, договор',
    phonetic: '[əˈɡriːmənt]',
  },
  { word: 'ah', type: 'exclam.', level: 'A2', translation: 'а! (междометие)', phonetic: '[ɑː]' },
  { word: 'ahead', type: 'adv.', level: 'B1', translation: 'впереди', phonetic: '[əˈhed]' },
  { word: 'aid', type: 'n., v.', level: 'B2', translation: 'помощь, помогать', phonetic: '[eɪd]' },
  { word: 'aim', type: 'v., n.', level: 'B1', translation: 'цель, целиться', phonetic: '[eɪm]' },
  { word: 'air', type: 'n.', level: 'A1', translation: 'воздух', phonetic: '[eər]' },
  {
    word: 'aircraft',
    type: 'n.',
    level: 'B2',
    translation: 'воздушное судно',
    phonetic: '[ˈeəkrɑːft]',
  },
  { word: 'airline', type: 'n.', level: 'A2', translation: 'авиакомпания', phonetic: '[ˈeəlaɪn]' },
  { word: 'airport', type: 'n.', level: 'A1', translation: 'аэропорт', phonetic: '[ˈeəpɔːt]' },
  {
    word: 'alarm',
    type: 'n. (B1), v. (B2)',
    level: 'B1/B2',
    translation: 'тревога; встревожить',
    phonetic: '[əˈlɑːm]',
  },
  { word: 'album', type: 'n.', level: 'B1', translation: 'альбом', phonetic: '[ˈælbəm]' },
  { word: 'alcohol', type: 'n.', level: 'B1', translation: 'алкоголь', phonetic: '[ˈælkəhɒl]' },
  {
    word: 'alcoholic',
    type: 'adj.',
    level: 'B1',
    translation: 'алкогольный',
    phonetic: '[ˌælkəˈhɒlɪk]',
  },
  { word: 'alive', type: 'adj.', level: 'A2', translation: 'живой', phonetic: '[əˈlaɪv]' },
  {
    word: 'all',
    type: 'det., pron. (A1), adv. (A2)',
    level: 'A1/A2',
    translation: 'все, весь',
    phonetic: '[ɔːl]',
  },
  {
    word: 'all right',
    type: 'adj./adv.',
    level: 'A2',
    translation: 'в порядке, хорошо',
    phonetic: '[ˌɔːl ˈraɪt]',
  },
  { word: 'allow', type: 'v.', level: 'A2', translation: 'позволять', phonetic: '[əˈlaʊ]' },
  { word: 'almost', type: 'adv.', level: 'A2', translation: 'почти', phonetic: '[ˈɔːlməʊst]' },
  {
    word: 'alone',
    type: 'adj./adv.',
    level: 'A2',
    translation: 'один, одиноко',
    phonetic: '[əˈləʊn]',
  },
  {
    word: 'along',
    type: 'prep., adv.',
    level: 'A2',
    translation: 'вдоль, вместе',
    phonetic: '[əˈlɒŋ]',
  },
  { word: 'already', type: 'adv.', level: 'A2', translation: 'уже', phonetic: '[ɔːlˈredi]' },
  { word: 'also', type: 'adv.', level: 'A1', translation: 'также, тоже', phonetic: '[ˈɔːlsəʊ]' },
  { word: 'alter', type: 'v.', level: 'B2', translation: 'изменять', phonetic: '[ˈɔːltər]' },
  {
    word: 'alternative',
    type: 'n. (A2), adj. (B1)',
    level: 'A2/B1',
    translation: 'альтернатива',
    phonetic: '[ɔːlˈtɜːrnətɪv]',
  },
  { word: 'although', type: 'conj.', level: 'A2', translation: 'хотя', phonetic: '[ɔːlˈðəʊ]' },
  { word: 'always', type: 'adv.', level: 'A1', translation: 'всегда', phonetic: '[ˈɔːlweɪz]' },
  { word: 'amazed', type: 'adj.', level: 'B1', translation: 'изумленный', phonetic: '[əˈmeɪzd]' },
  {
    word: 'amazing',
    type: 'adj.',
    level: 'A1',
    translation: 'удивительный',
    phonetic: '[əˈmeɪzɪŋ]',
  },
  {
    word: 'ambition',
    type: 'n.',
    level: 'B1',
    translation: 'амбиция, цель',
    phonetic: '[æmˈbɪʃn]',
  },
  { word: 'among', type: 'prep.', level: 'A2', translation: 'среди', phonetic: '[əˈmʌŋ]' },
  {
    word: 'amount',
    type: 'n. (A2), v. (B2)',
    level: 'A2/B2',
    translation: 'количество; составлять сумму',
    phonetic: '[əˈmaʊnt]',
  },
  { word: 'analysis', type: 'n.', level: 'B1', translation: 'анализ', phonetic: '[əˈnæləsɪs]' },
  {
    word: 'analyze',
    type: 'v.',
    level: 'A2',
    translation: 'анализировать',
    phonetic: '[ˈænəlaɪz]',
  },
  { word: 'ancient', type: 'adj.', level: 'A2', translation: 'древний', phonetic: '[ˈeɪnʃənt]' },
  { word: 'and', type: 'conj.', level: 'A1', translation: 'и', phonetic: '[ænd]' },
  { word: 'anger', type: 'n.', level: 'B2', translation: 'гнев', phonetic: '[ˈæŋɡər]' },
  { word: 'angle', type: 'n.', level: 'B2', translation: 'угол', phonetic: '[ˈæŋɡl]' },
  { word: 'angry', type: 'adj.', level: 'A1', translation: 'сердитый', phonetic: '[ˈæŋɡri]' },
  { word: 'animal', type: 'n.', level: 'A1', translation: 'животное', phonetic: '[ˈænɪml]' },
  { word: 'ankle', type: 'n.', level: 'A2', translation: 'лодыжка', phonetic: '[ˈæŋkl]' },
  {
    word: 'anniversary',
    type: 'n.',
    level: 'B2',
    translation: 'годовщина',
    phonetic: '[ˌænɪˈvɜːrsəri]',
  },
  { word: 'announce', type: 'v.', level: 'B1', translation: 'объявлять', phonetic: '[əˈnaʊns]' },
  {
    word: 'announcement',
    type: 'n.',
    level: 'B1',
    translation: 'объявление',
    phonetic: '[əˈnaʊnsmənt]',
  },
  { word: 'annoy', type: 'v.', level: 'B1', translation: 'раздражать', phonetic: '[əˈnɔɪ]' },
  { word: 'annoyed', type: 'adj.', level: 'B1', translation: 'раздраженный', phonetic: '[əˈnɔɪd]' },
  {
    word: 'annoying',
    type: 'adj.',
    level: 'B1',
    translation: 'раздражающий',
    phonetic: '[əˈnɔɪɪŋ]',
  },
  { word: 'annual', type: 'adj.', level: 'B2', translation: 'ежегодный', phonetic: '[ˈænjuəl]' },
  {
    word: 'another',
    type: 'det./pron.',
    level: 'A1',
    translation: 'другой, еще один',
    phonetic: '[əˈnʌðər]',
  },
  {
    word: 'answer',
    type: 'n., v.',
    level: 'A1',
    translation: 'ответ, отвечать',
    phonetic: '[ˈænsər]',
  },
  {
    word: 'anxious',
    type: 'adj.',
    level: 'B2',
    translation: 'тревожный, беспокоящийся',
    phonetic: '[ˈæŋkʃəs]',
  },
  {
    word: 'any',
    type: 'det., pron. A1, adv.',
    level: 'A2',
    translation: 'любой, какой-нибудь',
    phonetic: '[ˈeni]',
  },
  {
    word: 'anybody',
    type: 'pron.',
    level: 'A2',
    translation: 'кто-нибудь, любой',
    phonetic: '[ˈenibʌdi]',
  },
  {
    word: 'anymore',
    type: 'adv.',
    level: 'A2',
    translation: 'больше не (в отриц. предл.)',
    phonetic: '[ˌeniˈmɔːr]',
  },
  {
    word: 'anyone',
    type: 'pron.',
    level: 'A1',
    translation: 'кто угодно, кто-нибудь',
    phonetic: '[ˈeniwʌn]',
  },
  {
    word: 'anything',
    type: 'pron.',
    level: 'A1',
    translation: 'что угодно, что-нибудь',
    phonetic: '[ˈeniθɪŋ]',
  },
  {
    word: 'anyway',
    type: 'adv.',
    level: 'A2',
    translation: 'в любом случае, всё равно',
    phonetic: '[ˈeniweɪ]',
  },
  {
    word: 'anywhere',
    type: 'adv., pron.',
    level: 'A2',
    translation: 'везде, где-нибудь',
    phonetic: '[ˈeniwer]',
  },
  {
    word: 'apart',
    type: 'adv.',
    level: 'B1',
    translation: 'отдельно, в стороне',
    phonetic: '[əˈpɑːrt]',
  },
  {
    word: 'apartment',
    type: 'n.',
    level: 'A1',
    translation: 'квартира',
    phonetic: '[əˈpɑːrtmənt]',
  },
  {
    word: 'apologize',
    type: 'v.',
    level: 'B1',
    translation: 'извиняться',
    phonetic: '[əˈpɑːlədʒaɪz]',
  },
  { word: 'app', type: 'n.', level: 'A2', translation: 'приложение', phonetic: '[æp]' },
  {
    word: 'apparent',
    type: 'adj.',
    level: 'B2',
    translation: 'очевидный, видимый',
    phonetic: '[əˈpærənt]',
  },
  {
    word: 'apparently',
    type: 'adv.',
    level: 'B2',
    translation: 'по всей видимости',
    phonetic: '[əˈpærəntli]',
  },
  {
    word: 'appeal',
    type: 'n., v.',
    level: 'B2',
    translation: 'призыв, обращаться',
    phonetic: '[əˈpiːl]',
  },
  {
    word: 'appear',
    type: 'v.',
    level: 'A2',
    translation: 'появляться, казаться',
    phonetic: '[əˈpɪr]',
  },
  {
    word: 'appearance',
    type: 'n.',
    level: 'A2',
    translation: 'внешность, появление',
    phonetic: '[əˈpɪrəns]',
  },
  { word: 'apple', type: 'n.', level: 'A1', translation: 'яблоко', phonetic: '[ˈæpl]' },
  {
    word: 'application',
    type: 'n.',
    level: 'B1',
    translation: 'заявление, применение',
    phonetic: '[ˌæplɪˈkeɪʃn]',
  },
  {
    word: 'apply',
    type: 'v.',
    level: 'A2',
    translation: 'подавать заявку, применять',
    phonetic: '[əˈplaɪ]',
  },
  {
    word: 'appointment',
    type: 'n.',
    level: 'B1',
    translation: 'назначенная встреча',
    phonetic: '[əˈpɔɪntmənt]',
  },
  {
    word: 'appreciate',
    type: 'v.',
    level: 'B1',
    translation: 'ценить, быть благодарным',
    phonetic: '[əˈpriːʃieɪt]',
  },
  {
    word: 'approach',
    type: 'n., v.',
    level: 'B2',
    translation: 'подход, приближаться',
    phonetic: '[əˈproʊtʃ]',
  },
  {
    word: 'appropriate',
    type: 'adj.',
    level: 'B2',
    translation: 'соответствующий, уместный',
    phonetic: '[əˈproʊprieɪt]',
  },
  { word: 'approval', type: 'n.', level: 'B2', translation: 'одобрение', phonetic: '[əˈpruːvl]' },
  { word: 'approve', type: 'v.', level: 'B2', translation: 'одобрять', phonetic: '[əˈpruːv]' },
  {
    word: 'approximately',
    type: 'adv.',
    level: 'B1',
    translation: 'приблизительно',
    phonetic: '[əˈprɑːksɪmətli]',
  },
  { word: 'April', type: 'n.', level: 'A1', translation: 'апрель', phonetic: '[ˈeɪprəl]' },
  {
    word: 'architect',
    type: 'n.',
    level: 'A2',
    translation: 'архитектор',
    phonetic: '[ˈɑːrkɪtekt]',
  },
  {
    word: 'architecture',
    type: 'n.',
    level: 'A2',
    translation: 'архитектура',
    phonetic: '[ˈɑːrkɪtektʃər]',
  },
  { word: 'area', type: 'n.', level: 'A1', translation: 'область, район', phonetic: '[ˈeriə]' },
  {
    word: 'argue',
    type: 'v.',
    level: 'A2',
    translation: 'спорить, аргументировать',
    phonetic: '[ˈɑːrɡjuː]',
  },
  {
    word: 'argument',
    type: 'n.',
    level: 'A2',
    translation: 'аргумент, спор',
    phonetic: '[ˈɑːrɡjumənt]',
  },
  {
    word: 'arise',
    type: 'v.',
    level: 'B2',
    translation: 'возникать, появляться',
    phonetic: '[əˈraɪz]',
  },
  {
    word: 'arm',
    type: 'n.',
    level: 'A1',
    translation: 'рука (от плеча до кисти)',
    phonetic: '[ɑːrm]',
  },
  { word: 'armed', type: 'adj.', level: 'B2', translation: 'вооруженный', phonetic: '[ɑːrmd]' },
  { word: 'arms', type: 'n.', level: 'B2', translation: 'оружие', phonetic: '[ɑːrmz]' },
  { word: 'army', type: 'n.', level: 'A2', translation: 'армия', phonetic: '[ˈɑːrmi]' },
  {
    word: 'around',
    type: 'prep., adv.',
    level: 'A1',
    translation: 'вокруг, около',
    phonetic: '[əˈraʊnd]',
  },
  {
    word: 'arrange',
    type: 'v.',
    level: 'A2',
    translation: 'организовывать, договариваться',
    phonetic: '[əˈreɪndʒ]',
  },
  {
    word: 'arrangement',
    type: 'n.',
    level: 'A2',
    translation: 'договоренность, устройство',
    phonetic: '[əˈreɪndʒmənt]',
  },
  {
    word: 'arrest',
    type: 'v., n.',
    level: 'B1',
    translation: 'арестовывать, арест',
    phonetic: '[əˈrest]',
  },
  { word: 'arrival', type: 'n.', level: 'B1', translation: 'прибытие', phonetic: '[əˈraɪvl]' },
  { word: 'arrive', type: 'v.', level: 'A1', translation: 'прибывать', phonetic: '[əˈraɪv]' },
  { word: 'art', type: 'n.', level: 'A1', translation: 'искусство', phonetic: '[ɑːrt]' },
  { word: 'article', type: 'n.', level: 'A1', translation: 'статья', phonetic: '[ˈɑːrtɪkl]' },
  {
    word: 'artificial',
    type: 'adj.',
    level: 'B2',
    translation: 'искусственный',
    phonetic: '[ˌɑːrtɪˈfɪʃl]',
  },
  { word: 'artist', type: 'n.', level: 'A1', translation: 'художник', phonetic: '[ˈɑːrtɪst]' },
  {
    word: 'artistic',
    type: 'adj.',
    level: 'B2',
    translation: 'художественный',
    phonetic: '[ɑːrˈtɪstɪk]',
  },
  {
    word: 'as',
    type: 'prep. A1, adv., conj.',
    level: 'A2',
    translation: 'как, в качестве',
    phonetic: '[æz]',
  },
  { word: 'ashamed', type: 'adj.', level: 'B2', translation: 'стыдящийся', phonetic: '[əˈʃeɪmd]' },
  { word: 'aside', type: 'adv.', level: 'B2', translation: 'в сторону', phonetic: '[əˈsaɪd]' },
  { word: 'ask', type: 'v.', level: 'A1', translation: 'спрашивать, просить', phonetic: '[æsk]' },
  { word: 'asleep', type: 'adj.', level: 'A2', translation: 'спящий', phonetic: '[əˈsliːp]' },
  {
    word: 'aspect',
    type: 'n.',
    level: 'B2',
    translation: 'аспект, сторона',
    phonetic: '[ˈæspekt]',
  },
  { word: 'assess', type: 'v.', level: 'B2', translation: 'оценивать', phonetic: '[əˈses]' },
  {
    word: 'assessment',
    type: 'n.',
    level: 'B2',
    translation: 'оценка, оценивание',
    phonetic: '[əˈsesmənt]',
  },
  {
    word: 'assignment',
    type: 'n.',
    level: 'B1',
    translation: 'задание, назначение',
    phonetic: '[əˈsaɪnmənt]',
  },
  {
    word: 'assist',
    type: 'v.',
    level: 'B1',
    translation: 'помогать, содействовать',
    phonetic: '[əˈsɪst]',
  },
  {
    word: 'assistant',
    type: 'n., adj.',
    level: 'A2',
    translation: 'помощник',
    phonetic: '[əˈsɪstənt]',
  },
  {
    word: 'associate',
    type: 'v.',
    level: 'B2',
    translation: 'ассоциировать',
    phonetic: '[əˈsoʊʃieɪt]',
  },
  {
    word: 'associated',
    type: 'adj.',
    level: 'B2',
    translation: 'связанный (с чем-то)',
    phonetic: '[əˈsoʊʃieɪtɪd]',
  },
  {
    word: 'association',
    type: 'n.',
    level: 'B2',
    translation: 'ассоциация, объединение',
    phonetic: '[əˌsoʊʃiˈeɪʃn]',
  },
  { word: 'assume', type: 'v.', level: 'B2', translation: 'предполагать', phonetic: '[əˈsuːm]' },
  {
    word: 'at',
    type: 'prep.',
    level: 'A1',
    translation: 'в, у, на (предлог места/времени)',
    phonetic: '[æt]',
  },
  {
    word: 'athlete',
    type: 'n.',
    level: 'A2',
    translation: 'атлет, спортсмен',
    phonetic: '[ˈæθliːt]',
  },
  {
    word: 'atmosphere',
    type: 'n.',
    level: 'B1',
    translation: 'атмосфера',
    phonetic: '[ˈætməsfɪr]',
  },
  { word: 'attach', type: 'v.', level: 'B1', translation: 'прикреплять', phonetic: '[əˈtætʃ]' },
  {
    word: 'attack',
    type: 'n., v.',
    level: 'A2',
    translation: 'атака, атаковать',
    phonetic: '[əˈtæk]',
  },
  {
    word: 'attempt',
    type: 'n., v.',
    level: 'B2',
    translation: 'попытка, пытаться',
    phonetic: '[əˈtempt]',
  },
  {
    word: 'attend',
    type: 'v.',
    level: 'A2',
    translation: 'посещать, присутствовать',
    phonetic: '[əˈtend]',
  },
  { word: 'attention', type: 'n.', level: 'A2', translation: 'внимание', phonetic: '[əˈtenʃn]' },
  {
    word: 'attitude',
    type: 'n.',
    level: 'B1',
    translation: 'отношение, позиция',
    phonetic: '[ˈætɪtuːd]',
  },
  {
    word: 'attorney',
    type: 'n.',
    level: 'B2',
    translation: 'адвокат, юрист',
    phonetic: '[əˈtɜːrni]',
  },
  { word: 'attract', type: 'v.', level: 'B1', translation: 'привлекать', phonetic: '[əˈtrækt]' },
  {
    word: 'attraction',
    type: 'n.',
    level: 'B1',
    translation: 'аттракцион, притяжение',
    phonetic: '[əˈtrækʃn]',
  },
  {
    word: 'attractive',
    type: 'adj.',
    level: 'A2',
    translation: 'привлекательный',
    phonetic: '[əˈtræktɪv]',
  },
  {
    word: 'audience',
    type: 'n.',
    level: 'A2',
    translation: 'аудитория, зрители',
    phonetic: '[ˈɔːdiəns]',
  },
  { word: 'August', type: 'n.', level: 'A1', translation: 'август', phonetic: '[ˈɔːɡəst]' },
  { word: 'aunt', type: 'n.', level: 'A1', translation: 'тетя', phonetic: '[ænt]' },
  { word: 'author', type: 'n.', level: 'A2', translation: 'автор', phonetic: '[ˈɔːθər]' },
  {
    word: 'authority',
    type: 'n.',
    level: 'B1',
    translation: 'власть, полномочие',
    phonetic: '[əˈθɔːrəti]',
  },
  {
    word: 'automatic',
    type: 'n. B1',
    level: 'B1',
    translation: 'автоматический',
    phonetic: '[ˌɔːtəˈmætɪk]',
  },
  {
    word: 'automatically',
    type: 'adv.',
    level: 'B1',
    translation: 'автоматически',
    phonetic: '[ˌɔːtəˈmætɪkli]',
  },
  {
    word: 'available',
    type: 'adj.',
    level: 'A2',
    translation: 'доступный',
    phonetic: '[əˈveɪləbl]',
  },
  {
    word: 'average',
    type: 'adj., n. A2, v.',
    level: 'B1',
    translation: 'средний, в среднем',
    phonetic: '[ˈævərɪdʒ]',
  },
  { word: 'avoid', type: 'v.', level: 'A2', translation: 'избегать', phonetic: '[əˈvɔɪd]' },
  {
    word: 'award',
    type: 'n. A2, v.',
    level: 'B1',
    translation: 'награда, награждать',
    phonetic: '[əˈwɔːrd]',
  },
  { word: 'aware', type: 'adj.', level: 'B1', translation: 'осведомленный', phonetic: '[əˈwer]' },
  { word: 'away', type: 'adv.', level: 'A1', translation: 'прочь, далеко', phonetic: '[əˈweɪ]' },
  { word: 'awesome', type: 'adj.', level: 'A1', translation: 'потрясающий', phonetic: '[ˈɔːsəm]' },
  { word: 'awful', type: 'adj.', level: 'A2', translation: 'ужасный', phonetic: '[ˈɔːfl]' },
  { word: 'baby', type: 'n.', level: 'A1', translation: 'малыш', phonetic: '[ˈbeɪbi]' },
  {
    word: 'back',
    type: 'n., adv. A1, adj. A2, v.',
    level: 'B2',
    translation: 'назад, спина',
    phonetic: '[bæk]',
  },
  {
    word: 'background',
    type: 'n.',
    level: 'A2',
    translation: 'фон, предыстория',
    phonetic: '[ˈbækɡraʊnd]',
  },
  {
    word: 'backward',
    type: 'adv.',
    level: 'B1',
    translation: 'назад, наоборот',
    phonetic: '[ˈbækwərd]',
  },
  { word: 'bacteria', type: 'n.', level: 'B2', translation: 'бактерии', phonetic: '[bækˈtɪriə]' },
  { word: 'bad', type: 'adj.', level: 'A1', translation: 'плохой', phonetic: '[bæd]' },
  { word: 'badly', type: 'adv.', level: 'A2', translation: 'плохо, сильно', phonetic: '[ˈbædli]' },
  { word: 'bag', type: 'n.', level: 'A1', translation: 'сумка', phonetic: '[bæɡ]' },
  { word: 'bake', type: 'v.', level: 'B1', translation: 'печь, выпекать', phonetic: '[beɪk]' },
  {
    word: 'balance',
    type: 'n., v.',
    level: 'B1',
    translation: 'баланс, уравновешивать',
    phonetic: '[ˈbæləns]',
  },
  { word: 'ball', type: 'n.', level: 'A1', translation: 'мяч', phonetic: '[bɔːl]' },
  { word: 'ban', type: 'v., n.', level: 'B1', translation: 'запрещать, запрет', phonetic: '[bæn]' },
  { word: 'banana', type: 'n.', level: 'A1', translation: 'банан', phonetic: '[bəˈnænə]' },
  {
    word: 'band',
    type: 'n.',
    level: 'A1',
    translation: 'группа (муз.), лента',
    phonetic: '[bænd]',
  },
  {
    word: 'bank (money)',
    type: 'n.',
    level: 'A1',
    translation: 'банк (деньги)',
    phonetic: '[bæŋk]',
  },
  {
    word: 'bank (river)',
    type: 'n.',
    level: 'B1',
    translation: 'берег (реки)',
    phonetic: '[bæŋk]',
  },
  {
    word: 'bar',
    type: 'n. A1, v.',
    level: 'B2',
    translation: 'бар, плитка (шоколада)',
    phonetic: '[bɑːr]',
  },
  { word: 'barrier', type: 'n.', level: 'B2', translation: 'барьер', phonetic: '[ˈbæriər]' },
  {
    word: 'base',
    type: 'n., v.',
    level: 'B1',
    translation: 'база, основывать',
    phonetic: '[beɪs]',
  },
  { word: 'baseball', type: 'n.', level: 'A1', translation: 'бейсбол', phonetic: '[ˈbeɪsbɔːl]' },
  { word: 'based', type: 'adj.', level: 'A2', translation: 'основанный', phonetic: '[beɪst]' },
  { word: 'basic', type: 'adj.', level: 'B1', translation: 'базовый', phonetic: '[ˈbeɪsɪk]' },
  {
    word: 'basically',
    type: 'adv.',
    level: 'B2',
    translation: 'в основном',
    phonetic: '[ˈbeɪsɪkli]',
  },
  { word: 'basis', type: 'n.', level: 'B1', translation: 'основа', phonetic: '[ˈbeɪsɪs]' },
  {
    word: 'basketball',
    type: 'n.',
    level: 'A1',
    translation: 'баскетбол',
    phonetic: '[ˈbæskɪtbɔːl]',
  },
  { word: 'bath', type: 'n.', level: 'A1', translation: 'ванна', phonetic: '[bæθ]' },
  {
    word: 'bathroom',
    type: 'n.',
    level: 'A1',
    translation: 'ванная комната',
    phonetic: '[ˈbæθruːm]',
  },
  { word: 'battery', type: 'n.', level: 'B1', translation: 'батарейка', phonetic: '[ˈbætəri]' },
  {
    word: 'battle',
    type: 'n. B1, v.',
    level: 'B2',
    translation: 'битва, сражаться',
    phonetic: '[ˈbætl]',
  },
  {
    word: 'be',
    type: 'v., auxiliary v.',
    level: 'A1',
    translation: 'быть, являться',
    phonetic: '[biː]',
  },
  { word: 'beach', type: 'n.', level: 'A1', translation: 'пляж', phonetic: '[biːtʃ]' },
  { word: 'bean', type: 'n.', level: 'A2', translation: 'боб, фасоль', phonetic: '[biːn]' },
  {
    word: 'bear (deal with)',
    type: 'v.',
    level: 'B2',
    translation: 'выносить, терпеть',
    phonetic: '[ber]',
  },
  { word: 'bear (animal)', type: 'n.', level: 'A2', translation: 'медведь', phonetic: '[ber]' },
  {
    word: 'beat',
    type: 'v. A2, n.',
    level: 'B2',
    translation: 'бить, побеждать',
    phonetic: '[biːt]',
  },
  {
    word: 'beautiful',
    type: 'adj.',
    level: 'A1',
    translation: 'красивый',
    phonetic: '[ˈbjuːtɪfl]',
  },
  { word: 'beauty', type: 'n.', level: 'B1', translation: 'красота', phonetic: '[ˈbjuːti]' },
  { word: 'because', type: 'conj.', level: 'A1', translation: 'потому что', phonetic: '[bɪˈkəz]' },
  { word: 'become', type: 'v.', level: 'A1', translation: 'становиться', phonetic: '[bɪˈkʌm]' },
  { word: 'bed', type: 'n.', level: 'A1', translation: 'кровать', phonetic: '[bed]' },
  { word: 'bedroom', type: 'n.', level: 'A1', translation: 'спальня', phonetic: '[ˈbedruːm]' },
  { word: 'bee', type: 'n.', level: 'B1', translation: 'пчела', phonetic: '[biː]' },
  { word: 'beef', type: 'n.', level: 'A2', translation: 'говядина', phonetic: '[biːf]' },
  { word: 'beer', type: 'n.', level: 'A1', translation: 'пиво', phonetic: '[bɪr]' },
  {
    word: 'before',
    type: 'prep. A1, conj., adv.',
    level: 'A2',
    translation: 'до, перед',
    phonetic: '[bɪˈfɔːr]',
  },
  {
    word: 'beg',
    type: 'v.',
    level: 'B2',
    translation: 'умолять, попрошайничать',
    phonetic: '[beɡ]',
  },
  { word: 'begin', type: 'v.', level: 'A1', translation: 'начинать', phonetic: '[bɪˈɡɪn]' },
  { word: 'beginning', type: 'n.', level: 'A1', translation: 'начало', phonetic: '[bɪˈɡɪnɪŋ]' },
  { word: 'behave', type: 'v.', level: 'A2', translation: 'вести себя', phonetic: '[bɪˈheɪv]' },
  { word: 'behavior', type: 'n.', level: 'A2', translation: 'поведение', phonetic: '[bɪˈheɪvjər]' },
  {
    word: 'behind',
    type: 'prep., adv.',
    level: 'A1',
    translation: 'позади, за',
    phonetic: '[bɪˈhaɪnd]',
  },
  { word: 'being', type: 'n.', level: 'B2', translation: 'существо, бытие', phonetic: '[ˈbiːɪŋ]' },
  {
    word: 'belief',
    type: 'n.',
    level: 'B1',
    translation: 'вера, убеждение',
    phonetic: '[bɪˈliːf]',
  },
  { word: 'believe', type: 'v.', level: 'A1', translation: 'верить', phonetic: '[bɪˈliːv]' },
  { word: 'bell', type: 'n.', level: 'B1', translation: 'колокольчик, звонок', phonetic: '[bel]' },
  { word: 'belong', type: 'v.', level: 'A2', translation: 'принадлежать', phonetic: '[bɪˈlɔːŋ]' },
  {
    word: 'below',
    type: 'adv., prep.',
    level: 'A1',
    translation: 'ниже, под',
    phonetic: '[bɪˈloʊ]',
  },
  { word: 'belt', type: 'n.', level: 'A2', translation: 'ремень, пояс', phonetic: '[belt]' },
  { word: 'bend', type: 'v., n.', level: 'B1', translation: 'гнуть, изгиб', phonetic: '[bend]' },
  {
    word: 'benefit',
    type: 'n. A2, v.',
    level: 'B1',
    translation: 'выгода, приносить пользу',
    phonetic: '[ˈbenɪfɪt]',
  },
  { word: 'bent', type: 'adj.', level: 'B2', translation: 'изогнутый', phonetic: '[bent]' },
  {
    word: 'best',
    type: 'adj. A1, adv., n.',
    level: 'A2',
    translation: 'лучший',
    phonetic: '[best]',
  },
  {
    word: 'bet',
    type: 'v., n.',
    level: 'B2',
    translation: 'ставка, биться об заклад',
    phonetic: '[bet]',
  },
  {
    word: 'better',
    type: 'adj. A1, adv. A2, n.',
    level: 'B1',
    translation: 'лучше',
    phonetic: '[ˈbetər]',
  },
  {
    word: 'between',
    type: 'prep. A1, adv.',
    level: 'A2',
    translation: 'между',
    phonetic: '[bɪˈtwiːn]',
  },
  {
    word: 'beyond',
    type: 'prep., adv.',
    level: 'B2',
    translation: 'за пределами, вне',
    phonetic: '[bɪˈjɑːnd]',
  },
  { word: 'bicycle', type: 'n.', level: 'A1', translation: 'велосипед', phonetic: '[ˈbaɪsɪkl]' },
  { word: 'big', type: 'adj.', level: 'A1', translation: 'большой', phonetic: '[bɪɡ]' },
  { word: 'bike', type: 'n.', level: 'A1', translation: 'велосипед (разг.)', phonetic: '[baɪk]' },
  {
    word: 'bill',
    type: 'n. A1, v.',
    level: 'B2',
    translation: 'счет (к оплате), законопроект',
    phonetic: '[bɪl]',
  },
  { word: 'billion', type: 'number', level: 'A2', translation: 'миллиард', phonetic: '[ˈbɪljən]' },
  { word: 'biology', type: 'n.', level: 'A2', translation: 'биология', phonetic: '[baɪˈɑːlədʒi]' },
  { word: 'bird', type: 'n.', level: 'A1', translation: 'птица', phonetic: '[bɜːrd]' },
  { word: 'birth', type: 'n.', level: 'A2', translation: 'рождение', phonetic: '[bɜːrθ]' },
  {
    word: 'birthday',
    type: 'n.',
    level: 'A1',
    translation: 'день рождения',
    phonetic: '[ˈbɜːrθdeɪ]',
  },
  { word: 'bit', type: 'n.', level: 'A2', translation: 'кусочек, немного', phonetic: '[bɪt]' },
  { word: 'bite', type: 'v., n.', level: 'B1', translation: 'кусать, укус', phonetic: '[baɪt]' },
  { word: 'bitter', type: 'adj.', level: 'B2', translation: 'горький', phonetic: '[ˈbɪtər]' },
  { word: 'black', type: 'adj., n.', level: 'A1', translation: 'черный', phonetic: '[blæk]' },
  { word: 'blame', type: 'v., n.', level: 'B2', translation: 'винить, вина', phonetic: '[bleɪm]' },
  {
    word: 'blank',
    type: 'adj., n.',
    level: 'A2',
    translation: 'пустой, бланк',
    phonetic: '[blæŋk]',
  },
  { word: 'blind', type: 'adj.', level: 'B2', translation: 'слепой', phonetic: '[blaɪnd]' },
  {
    word: 'block',
    type: 'n. A2, v.',
    level: 'B1',
    translation: 'блок, блокировать',
    phonetic: '[blɑːk]',
  },
  { word: 'blog', type: 'n.', level: 'A1', translation: 'блог', phonetic: '[blɔːɡ]' },
  { word: 'blond', type: 'adj.', level: 'A1', translation: 'блондин', phonetic: '[blɑːnd]' },
  { word: 'blood', type: 'n.', level: 'A2', translation: 'кровь', phonetic: '[blʌd]' },
  { word: 'blow', type: 'v.', level: 'A2', translation: 'дуть', phonetic: '[bloʊ]' },
  { word: 'blue', type: 'adj., n.', level: 'A1', translation: 'синий', phonetic: '[bluː]' },
  {
    word: 'board',
    type: 'n. A2, v.',
    level: 'B1',
    translation: 'доска, садиться (на борт)',
    phonetic: '[bɔːrd]',
  },
  { word: 'boat', type: 'n.', level: 'A1', translation: 'лодка', phonetic: '[boʊt]' },
  { word: 'body', type: 'n.', level: 'A1', translation: 'тело', phonetic: '[ˈbɑːdi]' },
  { word: 'boil', type: 'v.', level: 'A2', translation: 'кипятить, варить', phonetic: '[bɔɪl]' },
  { word: 'bomb', type: 'n., v.', level: 'B1', translation: 'бомба, бомбить', phonetic: '[bɑːm]' },
  { word: 'bond', type: 'n.', level: 'B2', translation: 'связь, облигация', phonetic: '[bɑːnd]' },
  { word: 'bone', type: 'n.', level: 'A2', translation: 'кость', phonetic: '[boʊn]' },
  {
    word: 'book',
    type: 'n. A1, v.',
    level: 'A2',
    translation: 'книга, бронировать',
    phonetic: '[bʊk]',
  },
  { word: 'boot', type: 'n.', level: 'A1', translation: 'ботинок, сапог', phonetic: '[buːt]' },
  {
    word: 'border',
    type: 'n. B1, v.',
    level: 'B2',
    translation: 'граница, граничить',
    phonetic: '[ˈbɔːrdər]',
  },
  { word: 'bored', type: 'adj.', level: 'A1', translation: 'скучающий', phonetic: '[bɔːrd]' },
  { word: 'boring', type: 'adj.', level: 'A1', translation: 'скучный', phonetic: '[ˈbɔːrɪŋ]' },
  { word: 'born', type: 'v.', level: 'A1', translation: 'рожденный', phonetic: '[bɔːrn]' },
  {
    word: 'borrow',
    type: 'v.',
    level: 'A2',
    translation: 'одалживать (у кого-то)',
    phonetic: '[ˈbɑːroʊ]',
  },
  { word: 'boss', type: 'n.', level: 'A2', translation: 'босс, начальник', phonetic: '[bɔːs]' },
  { word: 'both', type: 'det./pron.', level: 'A1', translation: 'оба', phonetic: '[boʊθ]' },
  { word: 'bother', type: 'v.', level: 'B1', translation: 'беспокоить(ся)', phonetic: '[ˈbɑːðər]' },
  { word: 'bottle', type: 'n.', level: 'A1', translation: 'бутылка', phonetic: '[ˈbɑːtl]' },
  {
    word: 'bottom',
    type: 'n., adj.',
    level: 'A2',
    translation: 'дно, нижний',
    phonetic: '[ˈbɑːtəm]',
  },
  { word: 'bowl', type: 'n.', level: 'A2', translation: 'миска, чаша', phonetic: '[boʊl]' },
  { word: 'box', type: 'n.', level: 'A1', translation: 'коробка', phonetic: '[bɑːks]' },
  { word: 'boy', type: 'n.', level: 'A1', translation: 'мальчик', phonetic: '[bɔɪ]' },
  {
    word: 'boyfriend',
    type: 'n.',
    level: 'A1',
    translation: 'парень (друг)',
    phonetic: '[ˈbɔɪfrend]',
  },
  { word: 'brain', type: 'n.', level: 'A2', translation: 'мозг', phonetic: '[breɪn]' },
  { word: 'branch', type: 'n.', level: 'B1', translation: 'ветка, филиал', phonetic: '[bræntʃ]' },
  {
    word: 'brand',
    type: 'n., v.',
    level: 'B1',
    translation: 'бренд, клеймить',
    phonetic: '[brænd]',
  },
  { word: 'brave', type: 'adj.', level: 'B1', translation: 'смелый', phonetic: '[breɪv]' },
  { word: 'bread', type: 'n.', level: 'A1', translation: 'хлеб', phonetic: '[bred]' },
  {
    word: 'break',
    type: 'v., n.',
    level: 'A1',
    translation: 'ломать, перерыв',
    phonetic: '[breɪk]',
  },
  { word: 'breakfast', type: 'n.', level: 'A1', translation: 'завтрак', phonetic: '[ˈbrekfəst]' },
  { word: 'breast', type: 'n.', level: 'B2', translation: 'грудь', phonetic: '[brest]' },
  { word: 'breath', type: 'n.', level: 'B1', translation: 'дыхание, вдох', phonetic: '[breθ]' },
  { word: 'breathe', type: 'v.', level: 'B1', translation: 'дышать', phonetic: '[briːð]' },
  {
    word: 'breathing',
    type: 'n.',
    level: 'B1',
    translation: 'дыхание (процесс)',
    phonetic: '[ˈbriːðɪŋ]',
  },
  { word: 'bride', type: 'n.', level: 'B1', translation: 'невеста', phonetic: '[braɪd]' },
  { word: 'bridge', type: 'n.', level: 'A2', translation: 'мост', phonetic: '[brɪdʒ]' },
  { word: 'brief', type: 'adj.', level: 'B2', translation: 'краткий', phonetic: '[briːf]' },
  { word: 'bright', type: 'adj.', level: 'A2', translation: 'яркий', phonetic: '[braɪt]' },
  {
    word: 'brilliant',
    type: 'adj.',
    level: 'A2',
    translation: 'блестящий, выдающийся',
    phonetic: '[ˈbrɪliənt]',
  },
  { word: 'bring', type: 'v.', level: 'A1', translation: 'приносить', phonetic: '[brɪŋ]' },
  { word: 'broad', type: 'adj.', level: 'B2', translation: 'широкий', phonetic: '[brɔːd]' },
  {
    word: 'broadcast',
    type: 'v., n.',
    level: 'B2',
    translation: 'трансляция, транслировать',
    phonetic: '[ˈbrɔːdkæst]',
  },
  { word: 'broken', type: 'adj.', level: 'A2', translation: 'сломанный', phonetic: '[ˈbroʊkən]' },
  { word: 'brother', type: 'n.', level: 'A1', translation: 'брат', phonetic: '[ˈbrʌðər]' },
  { word: 'brown', type: 'adj., n.', level: 'A1', translation: 'коричневый', phonetic: '[braʊn]' },
  { word: 'brush', type: 'v., n.', level: 'A2', translation: 'чистить, щетка', phonetic: '[brʌʃ]' },
  { word: 'bubble', type: 'n.', level: 'B1', translation: 'пузырь', phonetic: '[ˈbʌbl]' },
  { word: 'budget', type: 'n.', level: 'B2', translation: 'бюджет', phonetic: '[ˈbʌdʒɪt]' },
  { word: 'build', type: 'v.', level: 'A1', translation: 'строить', phonetic: '[bɪld]' },
  { word: 'building', type: 'n.', level: 'A1', translation: 'здание', phonetic: '[ˈbɪldɪŋ]' },
  { word: 'bullet', type: 'n.', level: 'B2', translation: 'пуля', phonetic: '[ˈbʊlɪt]' },
  { word: 'bunch', type: 'n.', level: 'B2', translation: 'связка, пучок', phonetic: '[bʌntʃ]' },
  {
    word: 'burn',
    type: 'v. A2, n.',
    level: 'B2',
    translation: 'гореть, ожог',
    phonetic: '[bɜːrn]',
  },
  {
    word: 'bury',
    type: 'v.',
    level: 'B1',
    translation: 'хоронить, закапывать',
    phonetic: '[ˈberi]',
  },
  { word: 'bus', type: 'n.', level: 'A1', translation: 'автобус', phonetic: '[bʌs]' },
  { word: 'bush', type: 'n.', level: 'B2', translation: 'куст', phonetic: '[bʊʃ]' },
  { word: 'business', type: 'n.', level: 'A1', translation: 'бизнес, дело', phonetic: '[ˈbɪznəs]' },
  {
    word: 'businessman',
    type: 'n.',
    level: 'A2',
    translation: 'бизнесмен',
    phonetic: '[ˈbɪznəsmæn]',
  },
];

const allWords = [...rawWords];
let learnedWords = JSON.parse(localStorage.getItem('oxford_learned')) || [];
